atlanticwave-sdx/pce

tests/LoadBalancing/test_HeurCSP_Solver.py

Use correct import

---

.github/workflows/test.yml

Add a GitHub Actions workflow

---

.github/workflows/test.yml

Use the right requirements file in CI

---

.github/workflows/test.yml
setup.cfg

Similar to what's being done in sdx-lc, in https://github.com/atlanticwave-sdx/sdx-lc/pull/46.
See https://coveralls.io/builds/54026541 for an example coverage report.

Add coveralls.io coverage report

---

.github/workflows/test.yml

Use setup-python to cache dependencies

---

.github/workflows/test.yml

Update coveralls.io configuration

---

src/sdx/pce/load_balancing/te_solver.py
tests/test_te_solver.py

Refactor tests

---

src/sdx/pce/utils/functions.py
src/sdx/pce/utils/random_topology_generator.py

Remove unused `weight_assign()`

---

.github/workflows/test.yml
.gitignore
README.md
setup.cfg
src/sdx/pce/topology/temanager.py
tests/data/amlight.json
tests/data/sax.json
tests/data/zaoxi.json
tests/test_te_manager.py
tests/test_topology_grenmlconverter.py
tests/test_topology_manager.py
tox.ini

Issue is #95: pull `sdx.datamodel.topologymanager` modules from datamodel to pce, under `sdx.pce.topology`.
<del>This is stacked on top of PR #93, so that will have to get reviewed first.</del> (Edit: #93 is merged.)

Move connection breakdown logic to pce

---

README.md
tests/data/test_request.json

Update connection request description in README

---

scripts/simulation.py
src/sdx/pce/utils/random_connection_generator.py
tests/test_te_solver.py

Issue: #69 change the method name.

#69: change to a better method name (.generate())

---

src/sdx/pce/load_balancing/te_solver.py
src/sdx/pce/utils/random_connection_generator.py

1. update the TESolver.update_graph() with the new constant;
2. remove depleted functions in random_connection_generator

67.script step 1: Cleanup: #143

---

src/sdx/pce/heuristic/heur.py

pushing the heuristic solver with the new TESolver API

---

pyproject.toml
src/sdx_pce/topology/temanager.py
tests/test_te_manager.py

Get links in a connection path

---

pyproject.toml
src/sdx_pce/topology/manager.py
src/sdx_pce/topology/temanager.py
tests/test_te_manager.py

Add a topology map getter method

---

pyproject.toml

Use datamodel 2.0.6.dev1

---

src/sdx_pce/topology/grenmlconverter.py
tests/data/sax-2.json
tests/data/sdx.json

Add iso3166_2_lvl4

---

pyproject.toml
src/sdx_pce/topology/manager.py
src/sdx_pce/topology/temanager.py
tests/__init__.py
tests/data/test_request_amlight_user_port.json
tests/data/test_request_amlight_zaoxi_user_port.json
tests/test_te_manager.py
tests/test_te_solver_static.py

Relates to: https://github.com/atlanticwave-sdx/sdx-controller/issues/229
Fix getting ports when creating breakdown.
@YufengXin Can you check on the changes?

Update getting port when breakdown

---

pyproject.toml
src/sdx_pce/topology/grenmlconverter.py
src/sdx_pce/topology/manager.py
src/sdx_pce/topology/temanager.py
src/sdx_pce/utils/constants.py
src/sdx_pce/utils/functions.py
tests/data/sax-2-request-valid.json
tests/data/sax-2.json
tests/data/sdx.json
tests/data/test_request_amlight_user_port.json
tests/data/test_request_amlight_zaoxi_user_port.json
tests/test_path_function.py
tests/test_te_manager.py
tests/test_topology_manager.py

1. Use the opportunity to clean up some JSONs, esp. removing the legacy 'off:network" from all the urns.
2. Then adding managing the user port vlan ranges.
3. test the vlan assignment

183 about user specified vlan

---

.github/workflows/checks.yml
.github/workflows/test.yml
.mailmap
pyproject.toml

Changes:
- Update workflow steps to current versions.
- Update black to current version.
- Remove deprecated black configuration.
- Add a mailmap file, so that `git shortlog` etc will work correctly.

Housekeeping updates

---

tests/test_random_connection_generator.py
tests/test_random_topology_generator.py

added unittest for randomtopologygenerator and randomconnectiongenerator

add unittest for random generator

---

src/sdx_pce/topology/manager.py
src/sdx_pce/topology/temanager.py

Fix #205 
This PR basically enhances the `TEManager._update_vlan_tags_table` to also support updating the VLAN tag table upon topology update events (before, it was only updated when a topology was added, which led to an incomplete VLAN table for ports added later on during the SDX-Controller life cycle).
To be able to apply this change, some refactoring was necessary: 
- Renamed the `TopologyManager.get_port_map()` method to `TopologyManager.get_port_link_map()` to be more coherent with its actual code implementation. Additionally, the `TopologyManager._port_map` attribute was renamed to `TopologyManager._port_link_map`
- Added the `TopologyManager._port_map` attribute to be used as a mapping between port IDs and their actual Port object. Correspondent get method was also deployed. This …

Update vlan_tags_table upon topology update events

---

.github/workflows/test.yml
pyproject.toml
src/sdx_pce/topology/manager.py
src/sdx_pce/topology/temanager.py
src/sdx_pce/utils/constants.py
src/sdx_pce/utils/graphviz.py
src/sdx_pce/utils/random_topology_generator.py
tests/test_te_manager.py

162 re compute available bandwidth

---

pyproject.toml

Resolves #106.  Also enables [pytest-sugar](https://github.com/Teemu/pytest-sugar).

Ignore deprecation warning from grenml 

---

pyproject.toml
src/sdx_pce/topology/temanager.py

Resolves #241.  There are four `assert` statements still left, and I think it should be okay to keep them.

Replace `assert` statements

---

.github/workflows/test.yml
pyproject.toml

Re-enable coverage reporting to coveralls.io

---

pyproject.toml
src/sdx_pce/topology/manager.py
tests/data/sax-2-update.json
tests/data/sax-2.json

Fix https://github.com/atlanticwave-sdx/sdx-controller/issues/443
Fixed the Topology version and timestamp calculation based on the OXP. SDX-Controller should leverage what was sent from OXPs instead of based on the internal calculations.

Fix topology version and timestamp calculation

---

src/sdx_pce/topology/temanager.py

turn on _topology_lock when updating vlans and bw
