.github/workflows/test.yml
requirements.txt

Another attempt at #34.
GitHub Actions is trying to re-build numpy wheels and failing. Since `requirements.txt` is our cache key, updating it might invalidate the cache. It might be a good idea to use a newer numpy anyway.

Update numpy, kick GitHub Actions cache

---

.github/workflows/test.yml
README.md
setup.cfg
src/sdx/pce/utils/graphviz.py
src/sdx/pce/utils/random_topology_generator.py
tests/test_te_solver.py

Issue is #72. 
The function formerly known as `dot_file()` function has been moved to its own module, and renamed (to `read_dot_file()`), and refactored. Pygraphviz can be installed as an optional dependency, and pydot dependency has been removed.
The test that attempts to use the dot file will run only if either pygraphviz is installed. For testing with the optional dependency, run:
```
$ pip install .[test,pygraphviz]
$ pytest
```

Use pygraphviz optionally

---

.gitignore
src/sdx/pce/load_balancing/te_solver.py
src/sdx/pce/models.py
src/sdx/pce/topology/grenmlconverter.py
src/sdx/pce/topology/manager.py
src/sdx/pce/topology/temanager.py
tests/test_te_manager.py
tests/test_te_solver.py
tests/test_topology_graph.py
tests/test_topology_grenmlconverter.py

Issue is #97.
The big change is that TEManager now has a `_generate_connection_breakdown_tm()` method which takes a [ConnectionSolution](https://github.com/atlanticwave-sdx/pce/blob/2679f11b9eff96f34ad5f8c25e4e3a79a2f98166/src/sdx/pce/models.py#L53) input and breaks it down.  Tests have been updated, and things seem to work with JSON topology data and JSON connection requests without crashes.
The old `generate_connection_breakdown()` is kept around as `_generate_connection_breakdown_old()`, for now.  If/when this PR gets merged, we can perhaps plan on removing that after some testing with sdx-controller.  We will need to discuss a plan.
Backward compatibility is maintained by a little crude hack:
https://github.com/atlanticwave-sdx/pce/blob/a45b6397f6ac839bc7f9501b1375b097d4be344a/src/sdx/ …

Refactor connection breakdown logic

---

src/sdx/pce/load_balancing/te_solver.py
src/sdx/pce/topology/manager.py
src/sdx/pce/topology/temanager.py
tests/test_te_manager.py

Issue is #110.
Before, breakdown used to be like mentioned in the issue.  Now it is like:
```
{
"urn:ogf:network:sdx:topology:sax.net": {
"ingress_port": {
"id": "urn:ogf:network:sdx:port:zaoxi:A1:2",
"name": "Novi100:2",
"short_name": null,
"node": null,
"label_range": null,
"status": null,
"state": null,
"private_attributes": null
},
"egress_port": {
"id": "urn:ogf:network:sdx:port:sax:B2:4",
"label_range": [
"100-200",
"10001"
],
"name": "Novi02:4",
"node": "urn:ogf:network:sdx:node:sax:B2",
"short_name": "B2:3",
"status": "up"
}
}
}
```
The critical change is the line where TEManager adds topology the right way, so that `TEManager.topology_manager.topology_list` is correctly populated, so that `TEManager.topology_manager.get_domain_name()` returns the domain name instead of `None`. …

Add domains in path breakdowns

---

tests/__init__.py
tests/data/test_request.json
tests/data/topologies/amlight.json
tests/data/topologies/sax.json
tests/data/topologies/zaoxi.json
tests/test_te_manager.py

Issue is #114.  Changes:
- Every topology version has been corrected to be an integer (1 instead of 1.0). This way they will pass validation by connexion when we do a `POST /topology` at sdx-lc.
- The file `test_request.json` has been updated, to be consistent with [the one in sdx-controller](https://github.com/atlanticwave-sdx/sdx-controller/blob/main/tests/data/test_request.json).
- Updated a test (`test_connection_amlight_to_zaoxi`) to use the above test request.
- Added a test (`test_connection_amlight_to_zaoxi_with_merged_topology`) for to demonstrate that TEManager will resolve a node to the incorrected domain, when using the "merged" topology.

Multi-domain path breakdown investigation

---

CHANGELOG.md
setup.cfg

Issue is #116.  Changes:
- Add a changelog file, for a human-readable list of changes.
- Bump up version in setup.cfg.
Once this is merged, we can use `git+https://github.com/atlanticwave-sdx/pce@2.0.0` as a requirement in sdx-controller.

Prepare pce for 2.0.0

---

setup.cfg

Small change, because of #118.  We will need to tag pce 2.0.1 and use that in sdx-controller.

Bump up datamodel requirement

---

tests/data/topologies/amlight.json
tests/data/topologies/sax.json
tests/data/topologies/zaoxi.json

the ISO3166-2-lvl4 attribute in each of the nodes are required to uniquely identify each of the nodes and then map it accordingly on the MEICAN UI.

added atributeISO3166-2-lvl4

---

src/sdx_pce/topology/manager.py
src/sdx_pce/topology/temanager.py
src/sdx_pce/utils/exceptions.py
tests/test_te_manager.py
tests/test_topology_graph.py
tests/test_topology_grenmlconverter.py
tests/test_topology_manager.py

Fixes #124.  The main change is here:
https://github.com/atlanticwave-sdx/pce/blob/7460cab1da0bee2c62f31cfc3583604e4b51ebe9/src/sdx_pce/topology/temanager.py#L115-L126
Basically validates that a link has the expected properties.  Other changes are basically some quality-of-life stuff that emerged when I started looking into this:
- Adds a `sdx_pce.utils.exceptions.ValidationError` exception class to indicate errors.
- Hides `TopologyManager` implementation details.  Mark variables with `_` prefix indicating that they are private, and they must be accessed with getter methods now.  I found the direct use of `TopologyManager` member variables confusing.
- Updates the tests accordingly.

Add link property checks

---

README.md
src/sdx_pce/topology/temanager.py
tests/test_te_manager.py
tests/test_te_solver.py
tests/test_te_solver_static.py

Fixes #158.  Changes:
- Overhaul `TEManager` class such that `TEManager(topology_data, connection_request)` is changed to `TEManager(topology_data)`.
- Change `generate_connection_te()` to `generate_connection_matrix(traffic_request)` - now this method takes a connection request, not `TEManager` constructor.
- Update and add some tests accordingly.
- Add a test that uses two distinct connection requests.

Handle several connection requests in TEManager

---

src/sdx_pce/topology/temanager.py
tests/test_te_manager.py

As described by Italo in issue #175.
The unites sets the default to be a higher number, so this is why it's not covered.
in test_te_manager._make_traffic_matrix_from_list: line 170
if len(request) >= 4:
required_latency = request[3]
else:
required_latency = 100

#175: assign float(inf) to be the default request latency

---

src/sdx_pce/topology/temanager.py
tests/test_te_manager.py

1.  "min-max"
2. min
3. list [min, max] 
4. tuple (min, max)
@sajith, I did a quick  fix to allow all above format for vlan_range, esp, the tuple (), along with an unittest.
Well, port_handler._validate_vlan_range() would need to add the tuple too, and the unit tests cases.....
See if we all agree on this.

expand allowed vlan_range format

---

pyproject.toml
src/sdx_pce/topology/manager.py
tests/__init__.py
tests/test_topology_manager.py

Fix #196 
This pull request propose some changes on PCE TopologyManager component to make it comply with Topology Data Model Spec 2.0.0, specially for the inter domain computation.
Other changes will be needed in the near future to make it fully comply with spec 2.0.0 (e.g., private attributes, etc)

Changes to make PCE minimally compatible with topology spec 2.0.0

---

src/sdx_pce/topology/manager.py
tests/test_topology_manager.py

Fix #198 
- Adds a check for existing inter domain links before adding, then just update.
- Adding a mapping from Port status/state to Link status/state

Add check for existing inter domain link before adding

---

pyproject.toml
src/sdx_pce/topology/temanager.py

Fix #200 
Heads-UP: this PR depends on https://github.com/atlanticwave-sdx/datamodel/pull/141
- VLAN reservation routine had a bug where if the user requests a VLAN which is not on the VLAN table (meaning: the OXP does not specify that VLAN on their allowed range -- which by the way should be discussed), the `TEManager._reserve_vlan` call would fail with KeyError when running unit test:
```
FAILED tests/test_te_manager.py::TEManagerTests::test_connection_amlight_to_zaoxi_user_port_v2 - KeyError: 777
```
- Added backward compatibility to Port.label_range (also handled on datamodel PortHandler)

Fix error on vlan reservation and add backward compatibility to Port.label_range

---

src/sdx_pce/topology/manager.py

Fix #201 
Heads-Up: This PR sits on top of #207 -- it turns out the main branch was failing as documented on issue #200 
Heads-up1: this PR sits on top of atlanticwave-sdx/datamodel#140 (merged)
This pull request adds `Links.bandwidth` to inter domain Links based on Port's type.

Add Link.bandwidth to interdomain Links based on ports type

---

src/sdx_pce/topology/manager.py
tests/test_te_manager.py

Fix #203 
Heads-UP: this PR sits on top of #209 
- This PR adds a simple fix to the topology TE graph to omit unhealthy Links (i.e., Links that are not UP/Enabled)
- Adding unit tests to cover requests and topology changes for disabling links

Add extra check to TE Graph to remove disabled or down Links before computing the solution

---

src/sdx_pce/topology/manager.py
src/sdx_pce/topology/temanager.py
tests/test_te_manager.py

Related to https://github.com/atlanticwave-sdx/sdx-controller/issues/161
Heads-Up: sits on top of the other in-flight pull requests (#207 and #209 and #210) 
Basically adds a function which returns the failed links to be used after the topology update and help identify connections to be redeployed (https://github.com/atlanticwave-sdx/sdx-controller/issues/161)

Add means to calculate failed links on the topology

---

tests/test_te_manager.py

Related to https://github.com/atlanticwave-sdx/sdx-controller/issues/320.
According to the [Service Provisioning Data Model Specification](https://sdx-docs.readthedocs.io/en/latest/specs/provisioning-api-1.0.html), VLAN can be a "any", "untagged", "all", a range, etc, in addition to a number.  We should add more tests, perhaps starting with adding such requests in datamodel repository.

Add test for when VLAN requested is "any"

---

src/sdx_pce/topology/temanager.py
src/sdx_pce/utils/exceptions.py
tests/test_te_manager.py

Resolves #180.  This will need additional exception handling in SDX Controller.

Raise an error when `unreserve_vlan()` can't find the request ID

---

pyproject.toml
src/sdx_pce/topology/temanager.py
tests/__init__.py
tests/test_te_manager.py
tests/test_topology_manager.py

A new unit test, fix the bug with the corresponding test json in datamodel (3.0.0.dev1)

227 creating a connection to a port directly attached to a neighbor domain results in wrong breakdown

---

pyproject.toml
src/sdx_pce/topology/temanager.py
tests/__init__.py
tests/test_te_manager.py

Handle VLAN ranges in connection requests

---

pyproject.toml
src/sdx_pce/topology/temanager.py
src/sdx_pce/utils/exceptions.py
tests/data/sax-2-request-invalid.json
tests/data/sax-2-request-valid.json
tests/data/test_request_amlight.json
tests/data/test_request_amlight_user_port.json
tests/data/test_request_amlight_zaoxi_user_port.json

Enforce validation checks on connection requests.

datamodel new tag

---

.github/workflows/checks.yml
.github/workflows/test.yml
pyproject.toml
src/sdx_pce/topology/manager.py
src/sdx_pce/topology/temanager.py
src/sdx_pce/utils/constants.py
tests/data/sax-2-request-invalid.json
tests/data/sax-2-request-valid.json
tests/data/test_request_amlight.json
tests/data/test_request_amlight_user_port.json
tests/data/test_request_amlight_zaoxi_user_port.json
tests/test_te_manager.py
tests/test_topology_manager.py

1. take on the new tag from datamodel for error code handling
2. remove python 3.9 and 3.10
3. instead, update all persistent states, topology, bw, and available vlans in topology json.

245 a higher level api for state management

---

src/sdx_pce/topology/temanager.py
tests/test_te_manager.py

Fix #275 
Heads-UP: this PR sits on top of PR #277 
As described on issue #275, the VLAN table range contains a wrong value after some L2VPN provisioning. This PR fixes that bug and adds new unit test to covert similar situations.

Fix VLAN Table range calculation

---

pyproject.toml
src/sdx_pce/topology/temanager.py
tests/data/test_request_amlight_zaoxi_user_port.json
tests/test_te_manager.py
tests/test_topology_manager.py

Fix #276 
Related to https://github.com/atlanticwave-sdx/datamodel/issues/182
This PR has two main contributions:
- Enhancements for comply with datamodel recent adjustments related to OXP domains (https://github.com/atlanticwave-sdx/datamodel/pull/183)
- Fix test on breakdowns calculation (#276)

Fixes for OXP domains and fix test on breakdowns

---

src/sdx_pce/topology/temanager.py

Fix #275 
This PR adds a sanity check for processing an update on the VLAN table, to avoid ports of another domain to be wrongly included on a particular domain.
Here are the results of the end-to-end tests using this branch:
```
~/sdx-end-to-end-tests$ git diff docker-compose.yml
diff --git a/docker-compose.yml b/docker-compose.yml
index 8b430f2..4674937 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -158,6 +158,7 @@ services:
- .env
volumes:
- .:/sdx-end-to-end-tests
+      - ./pce/src/sdx_pce:/opt/venv/lib/python3.11/site-packages/sdx_pce
depends_on:
mongo:
condition: service_healthy
~/sdx-end-to-end-tests$ cd pce/
~/sdx-end-to-end-tests/pce$ git status
On branch fix/issue_controller_448
Your branch is up to date with 'origin/fix/issue_controller_448'.
(use "git push" to …
```

Avoid processing VLANs for ports outside the desired domain

---

pyproject.toml
src/sdx_pce/topology/manager.py
src/sdx_pce/topology/temanager.py

Fix atlanticwave-sdx/sdx-controller#448
Fix atlanticwave-sdx/sdx-controller#449
Fix atlanticwave-sdx/sdx-controller#342
Fix atlanticwave-sdx/sdx-end-to-end-tests#56
Fix atlanticwave-sdx/sdx-end-to-end-tests#55
Fix atlanticwave-sdx/sdx-end-to-end-tests#53
Fix atlanticwave-sdx/sdx-end-to-end-tests#49
Heads-up: this PR will sit on top of #283 
This PR apply some fixes and enhances on PCE to better handle topology updates and L2VPN request validations to provide proper return codes. Improvements are listed below:
- On topology updates, some fixes were applied to guarantee that residual_bandwidth local changes will be applied to all links after applying the changes to the SDX-Controller data. As discussed on Issue #286, the `Link.residual_bandwidth` is being used by SDX-Controller with a …

Fix topology update process and return code when validating L2VPN requests

---

pyproject.toml
src/sdx_pce/topology/temanager.py

Fix #279 
This PR adds the `max_number_oxps` QoS metric validation, which according to the specification should account for:
> max_number_oxps: The max_number_oxps sub-attribute describes the total number of OXPs in the path. When requesting a maximum number of OXPs in the path, the subkey "value" under max_number_oxps must be provided as an integer from 1 to 100.
I introduced `MAX_OXP_DEFAULT` as a way to differentiate cases where `max_number_oxps` was not required (it would be 101 as well, no difference)
```
~/sdx-end-to-end-tests$ git diff docker-compose.yml
diff --git a/docker-compose.yml b/docker-compose.yml
index 8b430f2..4674937 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -158,6 +158,7 @@ services:
- .env
volumes:
- .:/sdx-end-to-end-tests
+      - …
```

Fix max_number_oxps metric validation
